### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by Log1x** [groenroos/bulma-stylus#1]
Thanks a ton for doing this. Bulma not being in Stylus almost made me not use it despite really liking it.

Do you plan on keeping this actively maintained? I wouldn't mind helping with PR requests if need be. Looks like it's a little behind right now, but mainly just some small fixes.

**Comment by groenroos** [comment]
No problem at all! I really liked Bulma when I discovered it, but Sass is just so not palatable for me. There wasn't really anything workable out there, so I translated it myself for my own purposes.

I do indeed plan on keeping it up to date! I'll sync up with the original Bulma later today, but I always welcome help!

**Comment by groenroos** [comment]
I've now updated the translation to 0.4.0! I'll update to 0.4.1 once it's officially out.
