### ISSUE TITLE
mergeColorMaps() does not work

### ISSUE THREAD

**Issue by ppoffice** [groenroos/bulma-stylus#11]
The `mergeColorMaps()` function does not work as it uses `typeof($custom-colors) == 'map'` to detect whether the input custom color is a map. However, the return value of `typeof($custom-colors)` will always be `object` according to [an old Stylus doc](https://github.com/stylus/stylus/blob/cf3792a160ccb9b0702c1b503d410a8c35455824/docs/lists.md#list-detector), [hash/map's current implementation](https://github.com/stylus/stylus/blob/0.54.7/lib/parser.js#L2190-L2227), and my own experiments:

![image](https://user-images.githubusercontent.com/8849362/71538832-e4e1db80-28ff-11ea-8ff3-c34f5548ec11.png)

Perhaps we should use [`length` or `keys`](http://stylus-lang.com/docs/hashes.html#other-stuff) to check whether the input is a list, or simply skip the check.

**Comment by M-O-Z-G** [comment]
Working version is here https://github.com/groenroos/bulma-stylus/pull/12/commits/a5ba84bc3df92d995668d1f18d303329480ffdc0

**Comment by groenroos** [comment]
Merged the fix in #12 that should address this!
