### ISSUE TITLE
the mergeColorMaps function is not working

### ISSUE THREAD

**Issue by visomi-dev** [groenroos/bulma-stylus#16]
Hi everyone!

The function is not working for me, or maybe I am using it wrong, could you help me please?

$custom-colors = {
  "primary": $primary findColorInvert($primary),
  "secondary": $secondary findColorInvert($secondary),
  "terceary": $terceary findColorInvert($terceary),
  "anti-flash-white": $anti-flash-white findColorInvert($anti-flash-white),
  "facebook": $facebook findColorInvert($facebook),
  "twitter": $twitter findColorInvert($twitter),
  "illuminating-emerald": $illuminating-emerald findColorInvert($illuminating-emerald),
  "maastricht-blue": $maastricht-blue findColorInvert($maastricht-blue),
  "eerie-black": $eerie-black findColorInvert($eerie-black),
  "myrtle-green": $myrtle-green findColorInvert($myrtle-green),
  "pearl": $pearl findColorInvert($pearl),
  "tan": $tan findColorInvert($tan),
  "rubine": $rubine findColorInvert($rubine),
  "emerald": $emerald findColorInvert($emerald),
  "ruby": $ruby findColorInvert($ruby),
  "maya-blue": $maya-blue findColorInvert($maya-blue),
  "magic-potion": $magic-potion findColorInvert($magic-potion),
  "eucalyptus": $eucalyptus findColorInvert($eucalyptus),
  "kepel": $kepe findColorInvert($kepel)
}

**Comment by M-O-Z-G** [comment]
This error looks like `Unexpected type inside the list`? Then any of your color variables and/or `findColorInvert()` function may not be defined before your `$custom-colors` declaration, or not equal/returns any valid color value for a reason. 
It's possible, for example, if you writes your code just inside `initial-variables`, they are loaded before functions. Please, recheck your code to ensure that it's in order.

**Comment by visomi-dev** [comment]
it doesn't give me any error as such, it just doesn't add the custom colors to the colors map

**Comment by M-O-Z-G** [comment]
Be sure to declare this `$custom-colors` variable before initializing bulma-stylus, or before its `derived-variables` at least.

**Comment by groenroos** [comment]
@visomiDev Closing this issue as there hasn't been activity for a while and we haven't been able to confirm this. If it's still a problem, leave a comment with details and I'll take another look! Cheers!
