### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by AtrumSaurus** [groenroos/bulma-stylus#2]
Hi, I downloaded your repo, and great work transcribind the framework.
Though I am trying to compile your original repo with **gulp** and **gulp-stylus** under Windows, and i have the problem that output file, has several `@charset "utf-8";` declaration through the file (7 in total). This means i have to go iside the css and delete them manually. Same thing happens with pure stylus CLI.

I think this is due to some multiple `require`-ing in the stylus files.

Edit:

As I thought in every `_all.styl` file you have as first line `@charset "utf-8"`, this when merges the stylus in css generates multiple lines of that declarations in the output file. As soon as I can I am going to provide a pull request, but i think you can fix it faster than me :)

**Comment by groenroos** [comment]
Fixed by #3.
