### ISSUE TITLE
Update to 0.4.1

### ISSUE THREAD

**Issue by Log1x** [groenroos/bulma-stylus#4]
Hi friend.

Any ETA on an update to 0.4.1?

Thanks again for your fork. 😍 it.

**Comment by groenroos** [comment]
Hello mate!

Thanks for creating an issue, it would've gone past my radar without! I'm currently quite swamped, so it'll be a few days until I'll have the time to sit down a go through the 0.4.1 changes, which I recall there being numerous.

**Comment by Log1x** [comment]
Was curious if you started 0.4.1 yet? If not, I wouldn't mind helping you out a little and submitting a PR. Just didn't want to start on it and then have you surprise update it. 

Thanks!

**Comment by groenroos** [comment]
I haven't started it yet. Feel free to do a PR if you want to, it's very
much appreciated!

Remember to only translate up to the latest tag, and build the .css file
before committing.

**Comment by Log1x** [comment]
[#5](https://github.com/groenroos/bulma-stylus/pull/5)
