### ISSUE TITLE
Update to 0.7.1

### ISSUE THREAD

**Issue by groenroos** [groenroos/bulma-stylus#6]
The translation has fallen far behind of edge Bulma. Update the translation to the latest version.

**Comment by kvnxiao** [comment]
Are you using a tool to automate the translation of scss/sass files to stylus files?

**Comment by sookoll** [comment]
Latest is 0.7.4. Is this project alive?

**Comment by groenroos** [comment]
I'm still actively using this module in my personal projects, so I do have a vested interest in updating to the latest version, I've just been putting it off for other priorities. I'll see what I can do over the weekend!

**Comment by groenroos** [comment]
I've opened PR #7 to upgrade this project to the latest version of the Sass-based Bulma. However, there are still a few bugs to be worked out before I can merge that into master and release it.

**Comment by groenroos** [comment]
I've now merged that PR, and with a few caveats (please see #7), bulma-stylus is now fully caught up with the original Bulma!
